In [20]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',100)

data = pd.read_csv('covid_symptoms.csv')

In [130]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import mean_squared_error,f1_score,fbeta_score

x_train,x_test,y_train, y_test = train_test_split(data.loc[:,data.columns!='Infected'],data.Infected)
clf = RidgeClassifier().fit(x_train,y_train)
pred = clf.predict(x_test)
fbeta_score(y_test,pred,0.4)

1.0

In [131]:
x_train

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,None_Experiencing,Age_0-9,Age_10-19,Age_20-24,Age_25-59,Age_60+,Gender_Female,Gender_Male,Severity_Mild,Severity_Moderate,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes
251750,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0
8271,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,1,0,1,0,0,0,1
43638,0,0,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
19449,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
217446,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312389,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0
89821,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0
262424,1,0,0,0,0,0,1,1,1,1,0,0,1,0,0,0,1,0,0,0,1,1,0,0
136581,0,0,1,1,0,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1
193670,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0

In [155]:
from joblib import dump
dump(clf,'model.joblib')

In [158]:
new_sample = np.random.randint(0,2,(24)).reshape(1,-1)
clf.predict(new_sample)

In [159]:
clf.predict(x_test.iloc[0,:].values.reshape(1,-1))

array([1], dtype=int64)

In [154]:
x_train.iloc[:,20:21]

        Severity_Severe
251750                0
8271                  0
43638                 1
19449                 0
217446                1
...                 ...
312389                0
89821                 0
262424                1
136581                0
193670                0

[237600 rows x 1 columns]

In [28]:
def process_question(ans,answers):
    ans_values = [0 for i in range(len(answers))]
    
    for i in range(len(answers)):
        if ans==answers[i]:
            ans_values[i]=1
            break
    
    return ans_values

In [12]:
process_question('y',['dn','n','y'])

[0, 0, 1]

In [13]:
def age_group(age):
    age_group_values = [0 for i in range(5)]
    age_groups = [10,20,25,60,61]
    for i in range(len(age_groups)):
        if age<age_groups[i]:
            break
    age_group_values[i]=1
    return age_group_values

In [14]:
age_group(22)

[0, 0, 1, 0, 0]